# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gsi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchid', models.BigIntegerField(default=0)),
                ('steamid', models.CharField(blank=True, default='', max_length=32)),
                ('steamname', models.CharField(blank=True, default='', max_length=32)),
                ('team', models.CharField(blank=True, default='', max_length=1)),
                ('hp', models.PositiveSmallIntegerField(default=0)),
                ('mana', models.PositiveSmallIntegerField(default=0)),
                ('gpm', models.PositiveSmallIntegerField(default=0)),
                ('xpm', models.PositiveSmallIntegerField(default=0)),
                ('alive', models.BooleanField(default=False)),
            ],
        ),
    ]
